[build]
    functions = "functions"
[[redirects]]
    from = "api/*"
    to= ".netlify/functions/:splat"
    status = 200

[functions."schedule"]
schedule = "* * * * *"

[functions]
  node_bundler = "esbuild"